# Generated by Django 5.2.6 on 2025-09-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title'], 'verbose_name': 'خدمة', 'verbose_name_plural': 'الخدمات'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
    ]
