# Generated by Django 5.2.6 on 2025-09-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_service_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title'], 'verbose_name': 'مشروع', 'verbose_name_plural': 'المشاريع'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
    ]
