# Generated by Django 5.2.6 on 2025-09-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_news_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'خبر', 'verbose_name_plural': 'الأخبار'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='publish_date',
        ),
    ]
